http:
  routers:
    pve-web:
      rule: "Host(`pve.$DOMAIN`)"
      entryPoints: web-secure
      service: pve-web
      middlewares:
        - admin-chain
      tls:
        certResolver: cloudflare
        domains:
          - sans: "*.$DOMAIN"
    ops:
      rule: "Host(`ops.$DOMAIN`)"
      entryPoints: web-secure
      service: ops-web
      middlewares:
        - admin-chain
      tls:
        certResolver: cloudflare
        domains:
          - sans: "*.$DOMAIN"
    slskd:
      rule: "Host(`slskd.$DOMAIN`)"
      entryPoints: web-secure
      service: slskd-web
      middlewares:
        - admin-chain
      tls:
        certResolver: cloudflare
        domains:
          - sans: "*.$DOMAIN"
  serversTransports:
    pve-web:
      insecureSkipVerify: true
    unifi-web:
      insecureSkipVerify: true
  services:
    pve-web:
      loadBalancer:
        passHostHeader: true
        serversTransport: pve-web
        servers:
          - url: 
    ops-web:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: 
